#Setup Mysql If you want to use Mysql set true
MySQL:
  Use: false
  Host: localhost
  Username: root
  Password: password_here
  Port: '3306'
  Database: minecraft
  
AboutPK:
  #Send Broadcast message to near players
  Alert: true
  #Use ScoreBoard not chat
  UseScoreBoard: true
  # Warning Frequency
  AlertFrequency: 30
  # Radius of warning
  Radius: 10
  #Time the Player will be a PK  ( seconds )
  TimeOn: 25
  # How Much the player need to kill to turn into PK
  HowMuchForTurn: 3
  # Change Group if Player turn into PK
  ChangeGroup: false
  # Remove all others group if player turn into PK
  RemoveAllOthersGroup: false
  # What Group to change if you choose yes on last one
  NewGroup: pk
  # Setup your Bonus Type
  Bonus:
    # Enable Bonus for Player Killer
    Enable: false
    OnKill:
    # NumberOfKill : Id_Item,Id_Item
      '2': 34,35,36
      '3': '45'
      '4': 56,57,58
      
# Set language file you use 
Language: eng

# Use TagAPI plugin
TagAPI:
  Use: false
  TurnGreenAfterKillPk: false

AboutPlayer:
  NewBieProtect: 
    # If you want to protect newbie players
    Enable: true
    # Time on minutes
    NewBieProtectTime: 10m
