name: Mcpk
main: me.stutiguias.mcpk.Mcpk
version: ${project.version}
author: Stutiguias
commands:
   mcpk:
     description: Command MCPK reload
     usage: Use /mcpk for Help
permissions:
     mcpk.command.leftpk:
        description: Allow Command Remove PK Status
        default: false
     mcpk.command.reload:
        description: Allow Command Reload
        default: false
     mcpk.update:
        description: Allow update
        default: false