name: Mcpk
main: me.stutiguias.mcpk.Mcpk
version: ${project.version}
author: Stutiguias
depend : [Vault]
softdepend : [TagAPI]
commands:
   mcpk:
     description: Command MCPK reload
     usage: Use /mcpk for Help
permissions:
     mcpk.command.leftpk:
        description: Allow Command Remove PK Status
        default: false
     mcpk.command.reload:
        description: Allow Command Reload
        default: false
     mcpk.command.check:
        description: Allow
        default: true
     mcpk.admin:
         description: Admin
         children:
             mcpk.command.leftpk: true
             mcpk.command.reload: true
             mcpk.update: true
             mcpk.command.check: true