name: Minecraft Player Killer
main: me.stutiguias.mcpk.Mcpk
version: 0.4-DEV
author: Stutiguias
commands:
   mcpk:
     description: Command MCPK reload
     usage: /mcpk reload
permissions:
   