name: Mcpk
main: me.stutiguias.mcpk.Mcpk
version: 0.5
author: Stutiguias
commands:
   mcpk:
     description: Command MCPK reload
     usage: /mcpk reload
permissions:
     mcpk.command.leftpk:
        description: Allow Command Remove PK Status
        default: false